bypameladaniel/SOEN341

README.md
There were mardown issues. The team members names and technologies were appearing incorrectly. 
All fixed and ready for review please.
=> Fix all markdown issues + reformating Issue #14

README.md
As a developer, I want to update the README to reflect our transition from PHP to Python for the backend and include the tutorial name so that the documentation remains accurate and aligns with our technology stack.
=> Issue #24 : Update README to Include the New Languages and Frameworks Planned for Use

README.md
As a developer, I want to update the README to reflect our transition from the Flask framework to Django so that the documentation remains accurate and aligns with our updated technology stack.
=> Issue #28: Update README to Reflect Transition from Flask to Django

README.md
Revert the change that was made to main
=> Revert Issue #28: Update README to Reflect Transition from Flask to Django

README.md
As a developer, I want to update the README to reflect our transition from the Flask framework to Django so that the documentation remains accurate and aligns with our updated technology stack.
=> Update ReadMe to Reflect Transition from Flask to Django

README.md
Changed the database choice from mySQL to SQLite
=> Update the database choice in README

backend/requirements.txt
This pull request introduces a virtual environment (`venv`) to isolate the project dependencies and ensures consistency across all development setups. It also includes a `requirements.txt` file that lists the exact versions of the necessary Python packages.
1. **Navigate to the backend directory**:  
- First, clone the repository and navigate to the **backend** folder:  
```bash
cd backend
```
2. **Create and activate the virtual environment**:  
- Since the `venv` directory does not exist, let's create it:  
```bash
python3 -m venv venv
```  
- Then, activate the virtual environment:  
- On **Windows**:  
```bash
.\venv\Scripts\activate
```
- On **macOS/Linux**:  
```bash
source venv/bin/activate
```
3. **Install the required dependencies**:  
- Once the virtual environment is activated, …
=>  Issue #52: Set up virtual environment and add requirements.txt for consistent dependencies across all team members

backend/backend/settings.py, backend/channels/admin.py, backend/channels/apps.py, backend/channels/models.py, backend/channels/tests.py, backend/channels/views.py
Initialized "channels" app using Django's startapp command.
=> Create "channels" app

backend/app/serializers.py, backend/channels/serializers.py
The purpose of this pull request is to create serializers, essential to convert complex data types into Python data types that can be rendered into JSON, XML, or other content types. Two files were created, one serializer was for the user model in the app folder, and one containing the channel and message model in channels folder.
=> Issue #48: Create Serializers

frontend/src/App.tsx, frontend/src/components/Sidebar/DM-sidebar.css, frontend/src/components/Sidebar/DM-sidebar.tsx, frontend/src/components/Sidebar/group-sidebar.css, frontend/src/components/Sidebar/group-sidebar.tsx, frontend/src/components/layout.tsx, frontend/src/components/profile-page/profile.css, frontend/src/components/profile-page/profile.tsx, frontend/src/components/settings-page/settings.css, frontend/src/components/settings-page/settings.tsx
Both navigation sidebars (#43 and #44 ) are linked to the settings page (#45 ), the profile page (#42 ), and to each other.
I made the sidebars more dynamic to support future backend integration
The layout will have to be changed once the homepage (#46 ) is designed so the login/signup is done on the homepage before the sidebar and its features are displayed (for now, the group sidebar is displayed by default). 
More settings options TBD.
=> Designed the Settings page (#45) and Sidebars (#43 and #44)

frontend/src/components/messaging/ChatArea.css, frontend/src/components/messaging/ChatArea.tsx, frontend/src/components/messaging/ChatInputTextBox.tsx, frontend/src/components/messaging/MessageBubble.css, frontend/src/components/messaging/MessageBubble.tsx
The chat area was created in which messages appear when you send them, the final logic needs to be implemented to communicate with the server so this pull request completes sub tasks for #19 , #9  and #57.
=> 77 create the chat area

frontend/src/components/messaging/MessageBubble.css, frontend/src/components/messaging/MessageBubble.tsx
These modifications are part of the task 60 which is a sub task of issue #9 and #19.
=> 60 message bubble to show messages, task for issue #9 and #19

backend/app/models.py, backend/channels/models.py, backend/channels/urls.py, backend/channels/views.py
**Description:**
This PR introduces a new delete_message endpoint to allow users to delete messages. The implementation ensures that:
- Admins can delete any message in any channel.
=> Issue #71: Implement Api Endpoint to Delete a Message for Moderation

frontend/src/App.tsx, frontend/src/components/Sidebar/DM-sidebar.tsx, frontend/src/components/Sidebar/group-sidebar.tsx, frontend/src/components/home-page/Home.css, frontend/src/components/home-page/Home.tsx, frontend/src/components/layout.tsx, frontend/src/components/profile-page/profile.css, frontend/src/components/profile-page/profile.tsx, frontend/src/components/settings-page/settings.tsx
Merging home page design to branch 23-design-and-implement-role-UI
=> Issue #46 : Design a Home Page

backend/app/views.py, backend/backend/settings.py, backend/requirements.txt
Remove django allauth from the project and added the djangorestframework-simplejwt and PyJWT package to requirements.txt
=> Issue #105: remove django allauth from the project and update requirements.txt

backend/channels/urls.py, backend/channels/views.py
Implemented the API endpoint to delete a channel
=> Issue #69: Implement API endpoint Delete Channel

backend/channels/urls.py, backend/channels/views.py, frontend/src/App.tsx, frontend/src/components/Sidebar/group-sidebar.tsx, frontend/src/components/Sidebar/sidebar.css, frontend/src/components/chat-page/GroupChat.css, frontend/src/components/chat-page/GroupChat.tsx, frontend/src/components/messaging/ChatArea.css, frontend/src/components/messaging/ChatArea.tsx, frontend/src/components/messaging/ChatInputTextBox.css
I have added the functionality to see channels in the channel sidebar, then clicking on a channel joins it and retrieves messages in the chat area that opens. It is also possible to send these messages.
For issue #94
=> #94 link frontend messaging UI to backend

backend/backend/settings.py, backend/direct_messages/admin.py, backend/direct_messages/models.py
Direct Message Model : 
- A sender
- A receiver
- Content (Message) 
Also added the direct_messages into the installed apps that I had forgotten.
=> 91 implement a direct message model

README.md
Add the description of Core Feature 4 to the README file
=> Issue #166 Update README.md for Core Feature 4

frontend/src/components/profile-page/profile.tsx
Updated the profile picture code to immediately reflect changes by re-fetching user data after an upload. A page refresh is no longer required to see the new profile picture.
=> Issue #179 Fixed profile picture update issue without refresh

.github/workflows/main.yml, backend/requirements.txt, frontend/package-lock.json, frontend/package.json, frontend/src/components/Sidebar/group-sidebar.tsx, frontend/src/components/authentication/AuthForm.tsx, frontend/src/components/messaging/ChatArea.tsx, frontend/src/components/profile-page/profile.tsx
=> Issue #158: Setting up environment for tests

backend/channel/tests.py
To run tests on your local computer, run the following command 
`python manage.py test`
=> 189 fix the channel join create list tests

backend/channel/tests.py
Just a tiny mistake I made while merging my branches into sprint-4 that caused a bug
=> Issue #197: Tiny mistake made while merging corrected

backend/app/tests.py
It tests:
-That the registration works
-That there cant be duplicate usernames
=> Issue #188: Registration test case

backend/app/tests.py
For issue #190 . Implemented user logout test cases.
=> 190 logout test case

backend/app/tests.py, frontend/src/components/messaging/ChatArea.tsx
the array dependencies were causing the fetchmessages method in frontend to not work. the current code still needs to be fixed as it will not pass tests.
this will close #203 once complete
=> 203 fix fetchmessages and pass tests

backend/app/tests.py
This unit test tests:
1- modification of each field
2- non-authenticated access
3- partial updates
4- empty payload
=> Issue #191: modify user test

backend/direct_messages/tests.py
`python manage.py test` to run the all tests in my branch. Should finish with an OK for successfully ran tests.
=> Issue #187: Create the List All Direct Messages Unit Test
